version: '3.9'

services:
  db: 
    container_name: people-db
    image: "mcr.microsoft.com/mssql/server:latest"
    ports: 
      - "1433:1433"
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "#People@123"
      ACCEPT_EULA: "Y"
    restart: always
    networks:
      - people-back-net

  api:
    container_name: people-api
    build: ./API/People.API/
    ports: 
      - "5000:80"
      - "5001:443"
    environment:
      ASPNETCORE_ENVIRONMENT: development
    restart: always
    networks:
      - people-back-net
      - people-front-net
    depends_on:
      - db

  app:
    container_name: people-app
    build: ./APP/People/
    ports: 
      - "80:80"
    restart: always
    networks:
      - people-front-net
    depends_on:
      - api
    
networks:
  people-back-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
  people-front-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
